name: Weekly Accessibility Check

on:
  schedule:
    # Run every Sunday at 6:00 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  accessibility-comprehensive:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start preview server
        run: npm run preview &

      - name: Wait for server
        run: npx wait-on http://localhost:4173 --timeout 30000

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run comprehensive accessibility tests
        run: npx playwright test --project=${{ matrix.browser }} --grep="@accessibility" --reporter=line

      - name: Test all theme variations for accessibility
        run: npx playwright test --project=${{ matrix.browser }} --grep="@themes.*@accessibility" --reporter=line

      - name: Run full theme compatibility tests
        run: npx playwright test --project=${{ matrix.browser }} --grep="@themes" --reporter=line

      - name: Upload accessibility test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: accessibility-results-${{ matrix.browser }}
          path: |
            test-results/
            playwright-report/
          retention-days: 14

  accessibility-lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start preview server
        run: npm run preview &

      - name: Wait for server
        run: npx wait-on http://localhost:4173 --timeout 30000

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

  accessibility-summary:
    runs-on: ubuntu-latest
    needs: [accessibility-comprehensive, accessibility-lighthouse]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create accessibility report summary
        run: |
          echo "# Weekly Accessibility Report - $(date +'%Y-%m-%d')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- **Comprehensive Tests**: ${{ needs.accessibility-comprehensive.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Lighthouse Audit**: ${{ needs.accessibility-lighthouse.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Coverage" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ WCAG 2.1 AA compliance tests" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Screen reader compatibility" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Keyboard navigation" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Color contrast validation" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ All 6 theme variations" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Cross-browser testing (Chromium, Firefox, WebKit)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Lighthouse performance and accessibility scores" >> $GITHUB_STEP_SUMMARY